# Generated by Django 4.0.4 on 2022-05-24 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_alter_user_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('initial_price', models.FloatField()),
                ('description', models.CharField(blank=True, max_length=500)),
                ('image', models.ImageField(upload_to='images/')),
                ('is_in_auction', models.BooleanField(default=False)),
                ('is_selled', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.user')),
            ],
        ),
    ]
